import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer/Footer'
import menuH from '../public/images/icon-hamburger.svg'

const options = [
  { name: 'About' },
  { name: 'Careers' },
  { name: 'Events' },
  { name: 'Products' },
  { name: 'Support' }
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Loopstudios landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.topper}>
          <div className={styles.topperContent}>
            <div className={styles.topHeader}>
              <div className={styles.logo}></div>
              <label className={styles.hambMenu} htmlFor="ok">
                <Image src={menuH} width={40} height={40} alt="menu hamburguer" />
              </label>
              <input type="checkbox" className={styles.inputCheck} id="ok" />
              <div className={styles.menuDiv}>
                <div className={styles.menuContent}>
                  <ul>
                    {
                      options.map((item, i) => (
                        <li key={i}>{item.name}</li>
                      ))
                    }
                  </ul>
                </div>
              </div>
              <ul className={styles.headList}>
                <li>About</li>
                <li>Careers</li>
                <li>Events</li>
                <li>Products</li>
                <li>Support</li>
              </ul>
            </div>
            <div className={styles.topperText}>
              <h1>IMMERSIVE EXPERIENCES THAT DELIVER</h1>
            </div>
          </div>

        </section>

        <section className={styles.middle}>
          <div className={styles.midContainer}>
            <div className={styles.imgMid}></div>
            <div className={styles.textMid}>
              <div className={styles.textContentMid}>
                <h5>THE LEADER IN INTERACTIVE VR</h5>
                <p>Founded in 2011, Loopstudios has been producing world-class virtual reality
                  projects for some of the best companies around the globe. Our award-winning
                  creations have transformed businesses through digital experiences that bind
                  to their brand.</p>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.bottom}>
          <div className={styles.botContainer}>
            <div className={styles.headBottom}>
              <h1>OUR CREATIONS</h1>
              <button>SEE ALL</button>
            </div>
            <div className={styles.imgBottom}>

              <div className={styles.img1Bot} id={styles.img}>
                <h2>DEEP EARTH</h2>
              </div>

              <div className={styles.img2Bot} id={styles.img}>
                <h2>NIGHT ARCADE</h2>
              </div>

              <div className={styles.img3Bot} id={styles.img}>
                <h2>SOCCER TEAM VR</h2>
              </div>

              <div className={styles.img4Bot} id={styles.img}>
                <h2>THE GRID</h2>
              </div>

              <div className={styles.img5Bot} id={styles.img}>
                <h2>FROM UP ABOVE VR</h2>
              </div>

              <div className={styles.img6Bot} id={styles.img}>
                <h2>POCKET BOREALIS</h2>
              </div>

              <div className={styles.img7Bot} id={styles.img}>
                <h2>THE CURIOSITY</h2>
              </div>

              <div className={styles.img8Bot} id={styles.img}>
                <h2>MAKE IT FISHEYE</h2>
              </div>
              
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
    
  )
}
